ALTER TABLE GROUPS
ADD COLUMN created_at TIMESTAMP;

UPDATE GROUPS
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE GROUPS
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE GROUPS
ALTER COLUMN created_at SET NOT NULL;
