CREATE TABLE GROUP_MEMBERSHIPS (
id BIGSERIAL PRIMARY KEY,
user_id BIGINT NOT NULL,
group_id BIGINT NOT NULL,
role VARCHAR(50) DEFAULT 'MEMBER',
CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES USERS(id),
CONSTRAINT fk_group FOREIGN KEY(group_id) REFERENCES GROUPS(id),
CONSTRAINT unique_user_group UNIQUE(user_id, group_id)
);