INSERT INTO prompts (prompt) VALUES ('Tell us about something you achieved recently.');
INSERT INTO prompts (prompt) VALUES ('What''s something that made you smile recently?');
INSERT INTO prompts (prompt) VALUES ('What''s been on your mind lately?');
INSERT INTO prompts (prompt) VALUES ('What''s your current mood in one word?');
INSERT INTO prompts (prompt) VALUES ('Name something you''re grateful for.');
INSERT INTO prompts (prompt) VALUES ('Tell us about something you''re working towards.');
INSERT INTO prompts (prompt) VALUES ('Give a shout out to someone who has been there for you lately.');
INSERT INTO prompts (prompt) VALUES ('What is your main focus at the moment?');
INSERT INTO prompts (prompt) VALUES ('If you could drop everything to do something fun and spontaneous, what would it be?');
INSERT INTO prompts (prompt) VALUES ('Have you felt productive lately? Why?');
INSERT INTO prompts (prompt) VALUES ('What was the last interesting conversation you had?');
INSERT INTO prompts (prompt) VALUES ('How have you been spending your free time lately?');
INSERT INTO prompts (prompt) VALUES ('What are you watching right now? Would you recommend it?');
INSERT INTO prompts (prompt) VALUES ('Have you done anything fun lately?');
INSERT INTO prompts (prompt) VALUES ('Today''s mood...');
INSERT INTO prompts (prompt) VALUES ('What''s the best meal you''ve had recently?');
INSERT INTO prompts (prompt) VALUES ('How are you looking after yourself at the moment?');
INSERT INTO prompts (prompt) VALUES ('Is anything stressing you out at the moment?');
INSERT INTO prompts (prompt) VALUES ('Have you tried anything new lately? How did it go?');
INSERT INTO prompts (prompt) VALUES ('Are you looking forward to anything at the moment?');